update

diff --git a/functions/tagme b/functions/tagme
--- a/functions/tagme
+++ b/functions/tagme
@@ -3,6 +3,10 @@
 SECONDS=0
 scriptDir=$(dirname $0)
 currDir=$(/usr/bin/pwd)
+if [[ "$currDir" == "$HOME" ]]; then
+    echo "Please enter a workdir, don't run from top-dir directly, e.g. '$HOME'."
+	return
+fi
 
 # Change work dir to git-toplevel:
 # - if git-repo, the git-toplevel is the work dir
@@ -20,7 +24,8 @@ _ZT_ARGS_Usage=$(cat <<-END
 
 	Sample:
 	  tagme
-	  tagme -a md     ### create .tags into HOME accross multiple wiki dirs
+	  tagme -a wiki     ### create .tags into HOME accross multiple wiki dirs
+	  tagme -a md       ### markdown tag
 	  tagme -a link
 	  tagme -a save
 	  tagme -a clean
@@ -93,8 +98,13 @@ function cleanup() {
 }
 
 
+
 # Copy/Save clangd compile commands
 ClangdCompileFile() {
+	if [ "$action" != "default" ] && [ "$action" != "link" ] && [ "$action" != "save" ]; then
+		return
+	fi
+
 	skipClangNote="Skip '$ClangdFile': git-original-dir '${origDir}' not existed!"
 	if ! chk-var ${origDir} ; then
 		origDir=$(git config --get remote.origin.url)
@@ -186,157 +196,160 @@ fi
 
 #########################################################
 # Handle action=all/default/save/md {{{1
-if [ "$action" != "default" ] && [ "$action" != "save" ] && [ "$action" != "md" ]; then
+if [ "$action" != "default" ] && [ "$action" != "save" ] && [ "$action" != "md" ] && [ "$action" != "wiki" ]; then
 	echo "Can't handle action '$action', Exit!"
 	return 1
 fi
 
-if [ "$action" == "default" ] && [ "$action" == "save" ]; then
-	ClangdCompileFile
-fi
 
+# @return bool: return 0 for true and non-zero for false
+PrepareFileList() {
+	# Prepare file list
+	rm -fr ${tmpDir} 2> /dev/null
+	rm -f ${FLIST} 2> /dev/null
+	mkdir -p ${tmpDir}
 
-# Rebuild All
-rm -fr ${tmpDir} 2> /dev/null
-rm -f ${FLIST} 2> /dev/null
-mkdir -p ${tmpDir}
-
-# Issue "[: -ge: unary operator expected"
-# https://stackoverflow.com/questions/408975/compare-integer-in-bash-unary-operator-expected
-filecnt_c=0
-filecnt_python=0
-filecnt_rust=0
-filecnt_markdown=0
-if [[ "$action" == "md" ]]; then
-	if has-var TLDR_PAGES_SOURCE_LOCATION; then
-		filecnt_markdown=1024
-		dstDir="$HOME"
+	# Issue "[: -ge: unary operator expected"
+	# https://stackoverflow.com/questions/408975/compare-integer-in-bash-unary-operator-expected
+	filecnt_c=0
+	filecnt_python=0
+	filecnt_rust=0
+	filecnt_markdown=0
+	if [[ "$action" == "wiki" ]]; then
+		if has-var TLDR_PAGES_SOURCE_LOCATION; then
+			dstDir="$HOME/.cache"
+		else
+			echo "Please set multiple wiki dirs into var 'TLDR_PAGES_SOURCE_LOCATION' under '$action' action, Exit!"
+			return 1
+		fi
+	elif [ -f ${FLIST} ]; then
+		filecnt_c=1024
 	else
-		echo "Please set multiple wiki dirs into var 'TLDR_PAGES_SOURCE_LOCATION' under '$action' action, Exit!"
-		return 1
+		filecnt_c=$(find . -maxdepth 3 -type f -name '*.c' | wc -l)
+		filecnt_python=$(find . -maxdepth 3 -type f -name '*.py' | wc -l)
+		filecnt_rust=$(find . -maxdepth 3 -type f -name '*.rs' | wc -l)
+		filecnt_markdown=$(find . -maxdepth 3 -type f -name '*.md' | wc -l)
 	fi
-elif [ -f ${FLIST} ]; then
-	filecnt_c=1024
-else
-	filecnt_c=$(find . -maxdepth 3 -type f -name '*.c' | wc -l)
-	filecnt_python=$(find . -maxdepth 3 -type f -name '*.py' | wc -l)
-	filecnt_rust=$(find . -maxdepth 3 -type f -name '*.rs' | wc -l)
-	filecnt_markdown=$(find . -maxdepth 3 -type f -name '*.md' | wc -l)
-fi
 
-# Rust
-if [ $filecnt_rust -ge 3 ]; then
-	rusty-tags vi --output=".tags"
-	#return 0
-elif [ $filecnt_c -ge 3 ]; then
-	case "$tagscope" in
-	   "all")
-		   find -L . -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ${tmpDir}/cscope.f1
-	   ;;
-	   "wad")
-		   find daemon/wad -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ${tmpDir}/cscope.f1
-	   ;;
-	   *)
-		   find . -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ${tmpDir}/cscope.f1
-	   ;;
-	esac
+	# Rust
+	if [ $filecnt_rust -ge 3 ]; then
+		rusty-tags vi --output=".tags"
+		#return 0
+	elif [ $filecnt_c -ge 3 ]; then
+		if [ $filecnt_c -lt 1024 ]; then
+			clean_files+=("${FLIST}")
+		fi
 
-	wad_c=$(grep 'daemon/wad' ${tmpDir}/cscope.f1 | wc -l)
-	if [ $wad_c -ge 10 ]; then
-		cat ${tmpDir}/cscope.f1             | \
-			grep -v 'ccls-cache/'          | \
-			grep -v 'wad/ui/stdin/'        | \
-			grep -v 'wad/redirect/socket/' | \
-			grep -v 'wad/test/'            | \
-			grep -v 'wad/unittest/'        | \
-			grep -v 'wad/cache/test/'      | \
-			grep -v 'daemon/waagent/'      | \
-			grep -v 'linux/'               | \
-			grep -v 'linux-.*/'            | \
-			grep -v 'compress/'            | \
-			grep -v 'cooked/'              | \
-			grep -v 'fortitest/'           | \
-			grep -v 'linuxatm/'            | \
-			grep -v 'sysctl/'              | \
-			grep -v 'sysapi/stream_scan/tests/'  | \
-			grep -v 'router/'              | \
-			grep -v 'fortiweb/'            | \
-			grep -v 'fortitest/'           | \
-			grep -v 'tests/gtest/'         | \
-			grep -v 'tests/'               | \
-			grep -v 'tools/'               | \
-			grep -v '/_' \
-			> ${tmpDir}/cscope.f2
-	else
+		case "$tagscope" in
+		   "all")
+			   find -L . -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ${tmpDir}/cscope.f1
+		   ;;
+		   "wad")
+			   find daemon/wad -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ${tmpDir}/cscope.f1
+		   ;;
+		   *)
+			   find . -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ${tmpDir}/cscope.f1
+		   ;;
+		esac
+
+		wad_c=$(grep 'daemon/wad' ${tmpDir}/cscope.f1 | wc -l)
+		if [ $wad_c -ge 10 ]; then
+			cat ${tmpDir}/cscope.f1             | \
+				grep -v 'ccls-cache/'          | \
+				grep -v 'wad/ui/stdin/'        | \
+				grep -v 'wad/redirect/socket/' | \
+				grep -v 'wad/test/'            | \
+				grep -v 'wad/unittest/'        | \
+				grep -v 'wad/cache/test/'      | \
+				grep -v 'daemon/waagent/'      | \
+				grep -v 'linux/'               | \
+				grep -v 'linux-.*/'            | \
+				grep -v 'compress/'            | \
+				grep -v 'cooked/'              | \
+				grep -v 'fortitest/'           | \
+				grep -v 'linuxatm/'            | \
+				grep -v 'sysctl/'              | \
+				grep -v 'sysapi/stream_scan/tests/'  | \
+				grep -v 'router/'              | \
+				grep -v 'fortiweb/'            | \
+				grep -v 'fortitest/'           | \
+				grep -v 'tests/gtest/'         | \
+				grep -v 'tests/'               | \
+				grep -v 'tools/'               | \
+				grep -v '/_' \
+				> ${tmpDir}/cscope.f2
+		else
+			cat ${tmpDir}/cscope.f1            | \
+				grep -v 'ccls-cache/'          | \
+				grep -v '/_' \
+				> ${tmpDir}/cscope.f2
+		fi
+
+		sort ${tmpDir}/cscope.f2 > ${tmpDir}/cscope.f3
+		mv ${tmpDir}/cscope.f3 ${FLIST}
+	elif [[ "$action" == "wiki" ]]; then
+		clean_files+=("${tmpDir}/${FLIST}")
+
+		# multiple wiki dir
+		for oneDir in $(echo $TLDR_PAGES_SOURCE_LOCATION | tr ";,\ " "\n"); do
+			if [[ $oneDir = file://* ]]; then
+				oneDir=${oneDir:7:$}
+				if [ -d $oneDir ]; then
+					absDir=$(realpath "$oneDir")
+					find -L "$absDir" -name '*.md' >> ${tmpDir}/cscope.f1
+					continue
+				fi
+			fi
+		done
+
 		cat ${tmpDir}/cscope.f1            | \
 			grep -v 'ccls-cache/'          | \
 			grep -v '/_' \
 			> ${tmpDir}/cscope.f2
+		sort ${tmpDir}/cscope.f2 > ${tmpDir}/cscope.f3
+		mv ${tmpDir}/cscope.f3 ${tmpDir}/${FLIST}
+	elif [ $filecnt_markdown -ge 10 ]; then
+		clean_files+=("${FLIST}")
+
+		# current dir auto markdown
+		for i in "$list"; do
+			echo $i
+		done
+	else
+		FLIST=""
 	fi
 
-	sort ${tmpDir}/cscope.f2 > ${tmpDir}/cscope.f3
-	mv ${tmpDir}/cscope.f3 ${FLIST}
-elif [ $filecnt_markdown -eq 1024 ]; then
-	#clean_files+=("${FLIST}")
-
-	# multiple wiki dir
-	for oneDir in $(echo $TLDR_PAGES_SOURCE_LOCATION | tr ";,\ " "\n"); do
-		if [[ $oneDir = file://* ]]; then
-			oneDir=${oneDir:7:$}
-			if [ -d $oneDir ]; then
-				absDir=$(realpath "$oneDir")
-				find -L "$absDir" -name '*.md' >> ${tmpDir}/cscope.f1
-				continue
-			fi
-		fi
-
-		#echo "wilson no var:'$oneDir'"
-	done
-
-	cat ${tmpDir}/cscope.f1            | \
-		grep -v 'ccls-cache/'          | \
-		grep -v '/_' \
-		> ${tmpDir}/cscope.f2
-	sort ${tmpDir}/cscope.f2 > ${tmpDir}/cscope.f3
-	mv ${tmpDir}/cscope.f3 ${tmpDir}/${FLIST}
-elif [ $filecnt_markdown -ge 10 ]; then
-	clean_files+=("${FLIST}")
-
-	# current dir auto markdown
-	for i in "$list"; do
-		echo $i
-	done
-else
-	FLIST=""
-fi
+	return 0
+}
 
 
 GenTag()
 {
-	rm -f .tags 2> /dev/null
-	rm -f .tagx 2> /dev/null
-	rm -f GTAGS 2> /dev/null
-	rm -f GPATH 2> /dev/null
-	rm -f GRTAGS 2> /dev/null
-	rm -f tags 2> /dev/null
-	rm -f tagx 2> /dev/null
-	rm -f tags.lock 2> /dev/null
-	rm -f tags.temp 2> /dev/null
+	rm -f "${dstDir}/.tags" 2> /dev/null
+	rm -f "${dstDir}/.tagx" 2> /dev/null
+	rm -f "${dstDir}/GTAGS" 2> /dev/null
+	rm -f "${dstDir}/GPATH" 2> /dev/null
+	rm -f "${dstDir}/GRTAGS" 2> /dev/null
+	rm -f "${dstDir}/tags" 2> /dev/null
+	rm -f "${dstDir}/tagx" 2> /dev/null
+	rm -f "${dstDir}/tags.lock" 2> /dev/null
+	rm -f "${dstDir}/tags.temp" 2> /dev/null
 
 	#    /usr/bin/time gtags -f ${FLIST}
 	#    /usr/bin/time global -u -L ${FLIST}
-	rm -f .tags 2> /dev/null
-	rm -f .tagx 2> /dev/null
+	rm -f "${dstDir}/.tags" 2> /dev/null
+	rm -f "${dstDir}/.tagx" 2> /dev/null
 
 
 	fList=${FLIST}
 	if [ ! -z ${fList} ] && [ ! -f ${fList} ]; then
 		fList=''
-		if [ -f ${tmpDir}/${FLIST} ]; then
-			fList=${tmpDir}/${FLIST}
+		if [ -f "${tmpDir}/${FLIST}" ]; then
+			fList="${tmpDir}/${FLIST}"
 		fi
 	fi
 
+	echo "Creating tag: ${dstDir}/.tagx"
 	if [[ -z ${fList} ]]; then
 		# tage-emacs, tags-vim, tagx-fuzzy
 		#LC_COLLATE=C ctags -e ${CTAGS_FLAG} -f .tage -R . > /dev/null 2>&1
@@ -369,7 +382,13 @@ GenCcls()
 }
 
 pidTag=0
-if [[ "$action" == "default" || "$action" == "tag" || "$action" == "md" ]]; then
+PrepareFileList
+if [[ $? -ne 0 ]]; then
+	echo "PrepareFileList() fail! EXIT!"
+	return 1
+fi
+
+if [[ "$action" == "default" || "$action" == "tag" || "$action" == "md" || "$action" == "wiki" ]]; then
 	GenTag &
 	pidTag=$!
 fi
@@ -378,6 +397,10 @@ pidCscope=0
 if [[ "$action" == "default" || "$action" == "cscope" ]]; then
 	GenScope &
 	pidCscope=$!
+fi
+
+if [ "$action" == "default" ] && [ "$action" == "save" ]; then
+	ClangdCompileFile
 fi
 
 #pidCcls=0
